services:
    http_batch.handler:
        class: Hezarfen\HttpBatchBundle\Handler
        arguments:
            - '@kernel'

    http_batch.request.listener:
        class: Hezarfen\HttpBatchBundle\EventListener\RequestListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }