services:
    http_batch.handler:
        class: Ideasoft\HttpBatchBundle\Handler
        arguments:
            - '@kernel'

    http_batch.request.listener:
        class: Ideasoft\HttpBatchBundle\EventListener\RequestListener
        arguments:
            - '@annotations.reader',
            - '@http_batch.handler'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
